### ISSUE TITLE
When Posting to the Serial Comm it duplicates the message.

### ISSUE THREAD

**Issue by vinura** [mcagriaksoy/Serial-Communication-GUI-Program#3]
![image](https://user-images.githubusercontent.com/11626591/72659010-fb4ef480-39de-11ea-8476-91283556b07e.png)

When I sent 1 it duplicates it as 11. This happens for any string

**Comment by mcagriaksoy** [comment]
> Can you look that: It is never I think https://github.com/mcagriaksoy/TCP-Serial-UDP-Communication-GUI
edit: please try with v1.3.0 it resolved now...

**Comment by mcagriaksoy** [comment]
Please try with v1.3.0 it resolved now...
